---
- name: Déploiement automatique de l'application Nabiyou
  hosts: all
  become: yes  # C'est l'équivalent de taper "sudo" avant chaque commande

  tasks:
    - name: 1. Mettre à jour le catalogue (apt update)
      apt:
        update_cache: yes

    - name: 2. Installer Docker (apt install docker.io)
      apt:
        name: docker.io
        state: present

    - name: 3. Démarrer et activer Docker (systemctl start & enable)
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: 4. Nettoyer l'ancien conteneur (si existant)
      shell: docker rm -f nabiyou-app || true

    - name: 5. Lancer le conteneur Nabiyou App
      shell: docker run -d --name nabiyou-app -p 80:80 xmotech/nabiyou-app:v1
