---
- name: Déploiement automatique de l'application Nabiyou
  hosts: all
  become: yes  # C'est l'équivalent de taper "sudo" avant chaque commande

  tasks:
    - name: 1. Mettre à jour le catalogue (apt update)
      apt:
        update_cache: yes

    - name: 2. Installer Docker (apt install docker.io)
      apt:
        name: docker.io
        state: present

    - name: 3. Démarrer et activer Docker (systemctl start & enable)
      systemd:
        name: docker
        state: started
        enabled: yes

     - name: 4. Nettoyage total (Nom + Port)
      shell: |
        # 1. On supprime le conteneur par son nom s'il existe (même arrêté)
        docker rm -f nabiyou-app || true
        
        # 2. On supprime tout autre conteneur qui squatterait le port 80
        # Note le "-aq" qui cible TOUS les conteneurs (actifs ou non)
        port_containers=$(docker ps -aq --filter "publish=80")
        if [ ! -z "$port_containers" ]; then
          docker rm -f $port_containers
        fi
      args:
        executable: /bin/bash

    - name: 5. Lancer le conteneur Nabiyou App
      shell: docker run -d --name nabiyou-app -p 80:80 xmotech/nabiyou-app:v1
